<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.baosight.payment</groupId>
        <artifactId>payment-center-pom</artifactId>
        <version>1.1.0</version>
    </parent>

    <artifactId>payment-center-pay-gateway</artifactId>
    <description>支付接口网关</description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.ronan.common.validation</groupId>
            <artifactId>common-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.framework.database</groupId>
            <artifactId>database-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-common</artifactId>
        </dependency>

        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-mch-api</artifactId>
            <version>${payment-center-api.version}</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-system-api</artifactId>
            <version>${payment-center-api.version}</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>${bouncycastle.version}</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-order-api</artifactId>
            <version>${payment-center-api.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.distributedid</groupId>
            <artifactId>distributed-id-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>pay</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-notify-api</artifactId>
            <version>${payment-center-api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
<!--    <dependencies>-->
<!--        <dependency>-->
<!--            <groupId>com.baosight.saas</groupId>-->
<!--            <artifactId>saas-common-auth</artifactId>-->
<!--        </dependency>-->
    </dependencies>

</project>
