stages:
  - build
  - package
  - upload

build-job:
  stage: build
  script:
    - echo "构建项目"
    - echo "Compile complete."

package-job:
  stage: package
  script:
    - echo "打包项目"
    - echo "打包中...."

upload-job:
  stage: upload
  script:
    - echo "上传项目"
    - echo "上传中"