<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.baosight.payment</groupId>
    <artifactId>payment-center-pom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <modules>
        <module>payment-center-system</module>
        <module>payment-center</module>
        <module>payment-center-common</module>
        <module>payment-center-mch</module>
        <module>payment-center-access</module>
        <module>payment-center-pay-gateway</module>
        <module>payment-center-api</module>
        <module>pay</module>
        <module>payment-center-isv</module>
        <module>payment-center-trade</module>
        <module>payment-center-notify</module>
        <module>payment-center-accounting</module>
        <module>pay-center-channel</module>
        <module>pay-center-cashier</module>
        <module>pay-center-check</module>
        <module>pay-center-settlement</module>
        <module>payment-center-partner-common</module>
    </modules>

    <properties>
        <revision>1.1.0</revision>
        <maven-compiler-plugin.version>3.9.0</maven-compiler-plugin.version>
        <maven-resources-plugin.version>3.1.0</maven-resources-plugin.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>3.1.9</spring-boot.version>
        <spring-cloud-alibaba.version>2022.0.0.0</spring-cloud-alibaba.version>
        <spring-cloud.version>2022.0.5</spring-cloud.version>
        <mapstruct.version>1.5.5.Final</mapstruct.version>
        <common-auth.version>1.0.0</common-auth.version>
        <database-spring.version>1.1.0</database-spring.version>
        <common.version>1.0.0</common.version>
        <distributed-id.version>1.0.0</distributed-id.version>
        <saas-common.version>1.0.3</saas-common.version>
        <payment-center-api.version>1.0.0</payment-center-api.version>
        <web-framework.version>1.1.0</web-framework.version>
        <saas-common-web.version>1.0.3</saas-common-web.version>
        <mysql.version>8.0.33</mysql.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!--spring cloud alibaba-->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--spring boot-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--spring cloud-->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
<!--            <dependency>-->
<!--                <groupId>com.baosight.saas</groupId>-->
<!--                <artifactId>saas-common-auth</artifactId>-->
<!--                <version>${common-auth.version}</version>-->
<!--            </dependency>-->
            <!--            <dependency>-->
            <!--                <groupId>com.baosight.database</groupId>-->
            <!--                <artifactId>database-spring-boot-starter</artifactId>-->
            <!--                <version>1.0.5</version>-->
            <!--            </dependency>-->
            <dependency>
                <groupId>com.baosight.framework.database</groupId>
                <artifactId>database-spring-boot-starter</artifactId>
                <version>${database-spring.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baosight.payment</groupId>
                <artifactId>payment-center-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!--            <dependency>-->
            <!--                <groupId>com.baosight.saas.oauth</groupId>-->
            <!--                <artifactId>saas-oauth-feign</artifactId>-->
            <!--                <version>1.0.0</version>-->
            <!--            </dependency>-->

            <dependency>
                <groupId>com.baosight.payment</groupId>
                <artifactId>payment-center-mch</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baosight.payment</groupId>
                <artifactId>payment-center-system</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baosight.payment</groupId>
                <artifactId>payment-center-pay-gateway</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baosight.payment</groupId>
                <artifactId>pay-center-settlement</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baosight.payment</groupId>
                <artifactId>payment-center-notify</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baosight.payment</groupId>
                <artifactId>payment-center-accounting</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baosight.payment</groupId>
                <artifactId>payment-center-isv</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baosight.payment</groupId>
                <artifactId>payment-center-trade</artifactId>
                <version>${project.version}</version>
            </dependency>
<!--            <dependency>-->
<!--                <groupId>com.baosight.saas</groupId>-->
<!--                <artifactId>saas-common-web</artifactId>-->
<!--                <version>${project.version}</version>-->
<!--            </dependency>-->
            <dependency>
                <groupId>com.baosight.utils</groupId>
                <artifactId>common-util-validation</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.baosight.distributedid</groupId>
                <artifactId>distributed-id-spring-boot-starter</artifactId>
                <version>${distributed-id.version}</version>
            </dependency>
            <dependency>
                <groupId>com.ronan.common</groupId>
                <artifactId>common-all</artifactId>
                <version>${common.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.baosight.saas</groupId>
                <artifactId>saas-common-dependencies</artifactId>
                <version>${saas-common.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.baosight.payment</groupId>
                <artifactId>payment-center-api</artifactId>
                <version>${payment-center-api.version}</version>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.baosight.web.framework</groupId>
                <artifactId>web-spring-boot-dependencies</artifactId>
                <version>${web-framework.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring</artifactId>
                <version>3.5.15</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-core</artifactId>
                <version>3.5.15</version>
            </dependency>


        </dependencies>
    </dependencyManagement>
    <build>
        <finalName>${project.name}</finalName>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                    <configuration>
                        <layers>
                            <enabled>true</enabled>
                        </layers>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>repackage</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${maven-resources-plugin.version}</version>
                    <configuration>
                        <encoding>${project.build.sourceEncoding}</encoding>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>2.18.0</version>
                </plugin>
                <!-- 解析版本号 -->
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>3.3.0</version>
                    <executions>
                        <execution>
                            <id>parse-version</id>
                            <goals>
                                <goal>parse-version</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <source>17</source>
                        <target>17</target>
                        <encoding>UTF-8</encoding>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${mapstruct.version}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>1.18.30</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok-mapstruct-binding</artifactId>
                                <version>0.2.0</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>