<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.baosight.payment</groupId>
        <artifactId>payment-center-pom</artifactId>
        <version>1.1.0</version>
    </parent>

    <artifactId>payment-center-system</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
<!--    <dependencies>-->
<!--        <dependency>-->
<!--            <groupId>com.baosight.saas</groupId>-->
<!--            <artifactId>saas-common-auth</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.baosight.saas</groupId>-->
<!--            <artifactId>saas-common-dynamic-form</artifactId>-->
<!--            <version>1.0.0</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.67</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.12.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.distributedid</groupId>
            <artifactId>distributed-id-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-system-api</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-mch-api</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ronan.common</groupId>
            <artifactId>common-string</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment.channel</groupId>
            <artifactId>payment-center-channel-api</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.saas</groupId>
            <artifactId>saas-common-dynamic-form</artifactId>
        </dependency>

    </dependencies>

</project>