<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.baosight.payment</groupId>
        <artifactId>payment-center-pom</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>pay-center-check</artifactId>
    <description>支付中心-{对账模块} </description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.baosight.saas</groupId>
            <artifactId>saas-common-auth</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.saas</groupId>
            <artifactId>saas-common-dynamic-form</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-mch-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-isv-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.mq.rocket</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-notify-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-order-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-check-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-system-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <version>2.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>pay-center-settlement</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</project>