<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.baosight.payment</groupId>
        <artifactId>payment-center</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>payment-center-service</artifactId>

    <version>1.0.69-SNAPSHOT</version>

    <properties>
        <buildNumber>1</buildNumber>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-system</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>

            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.saas.oauth</groupId>
            <artifactId>saas-oauth-feign</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-mch</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-isv</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-pay-gateway</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-trade</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-notify</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>payment-center-accounting</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>pay-center-check</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.baosight.payment</groupId>
            <artifactId>pay-center-settlement</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>11.9.1</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
            <version>11.9.1</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>pay-service-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <layers>
                        <enabled>true</enabled>
                    </layers>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>